
## OHDSI-UK

### Background 

The United Kingdom has more than 20 Data Partners in the EHDEN network and several EHDEN-certified SMEs. The UK scientific network is dynamic and research active, with numerous initiatives in the fields of health informatics, health data sciences, pharmacoepidemiology, and related areas.

Many UK partners have made substantial contributions to recent EHDEN- and OHDSI-sponsored research, and key national players like Health Data Research UK and the National Institute for Health and Care Excellence (NICE) are increasingly interested in the use of OMOP for federated analytics nationally.

### Objectives 

The aims of the UK national node include:

- To adopt OHDSI’s mission, vision, and values
- To facilitate the coordination of national members at a national and international level with OHDSI and EHDEN partners
- To promote the OHDSI mission in the UK in collaboration with relevant national stakeholders including academia, healthcare organizations, HTA agencies, regulators, patient organizations, policy makers, clinical guideline developers and pharmaceutical and life science industry
- To initiate and/or collaborate in relevant national research collaborations and co-ordination with European and global OHDSI initiatives
- To organize training programs in the field of Health Data Sciences and related areas
- To engage with the European and global OHDSI leadership

### Leading Organisation 

Health Data Sciences Section, Botnar Research Centre, University of Oxford

## Members / Data Partners 

The not currently has several data partners you can find them in [Data Partners](data_partners.qmd).

Akrivia Health
Aridhia DRE
Barts Health NHS Trust
British Heart Foundation Data Science Centre
Clinical Architecture Ltd
Clinical Practice Research Datalink
Connected Bradford
DataLoch
Edinburgh Cancer Centre
GOSH
Health Data Research UK
King's College London
Lancashire Teaching Hospitals NHS Foundation Trust
Leeds Teaching Hospitals
NICE
Nottingham University Hospitals Trust
Optimum Patient Care
Queen Mary University of London
UK National Neonatal Research Database
University College London
University College London Hospitals
Health Informatics Centre
University of Dundee
University of Edinburgh
University of Nottingham
How to contribute?

Any UK-based institution interested to join the UK OHDSI Node should get in touch with the coordinator: prietoalhambra@ohdsi.org


